/**
 * Types modelling the X-Road Message Protocol for REST.
 * Reference: https://docs.x-road.global/Protocols/pr-rest_x-road_message_protocol_for_rest.html
 */

/**
 * Identifier of an X-Road member or service.
 * Format: INSTANCE/CLASS/MEMBER[/SUBSYSTEM][/SERVICECODE]
 * Example: "DEV/COM/222/TESTSERVICE/helloService"
 */
export type XRoadIdentifier = string;

export type XRoadHttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface XRoadRequestHeaders {
  /** Required. Identifies the calling client (consumer). */
  "X-Road-Client": XRoadIdentifier;
  /** Recommended. UUID correlation id for the message. Auto-generated when absent. */
  "X-Road-Id"?: string;
  /** Optional. End user identifier prefixed with ISO country code. */
  "X-Road-UserId"?: string;
  /** Optional. Free-form application or document identifier. */
  "X-Road-Issue"?: string;
  Accept?: string;
}

export interface XRoadResponseHeaders {
  /** Echoes the consumer identifier. */
  "x-road-client"?: XRoadIdentifier;
  /** Identifies the service the security server routed to. */
  "x-road-service"?: XRoadIdentifier;
  /** Same correlation id (echoed or generated by the provider's SS). */
  "x-road-id"?: string;
  /** base64(SHA512(headers)+SHA512(body)) — provider's SS attaches this. */
  "x-road-request-hash"?: string;
  /** Provider's SS request id for cross-system tracing. */
  "x-road-request-id"?: string;
}

export interface XRoadCallOptions {
  /** Service identifier to call, e.g. "DEV/COM/222/TESTSERVICE/helloService". */
  service: XRoadIdentifier;
  /** Optional sub-path appended after the service id, e.g. "/v1/pets/1". */
  path?: string;
  /** Optional query string parameters. */
  query?: Record<string, string>;
  method?: XRoadHttpMethod;
  body?: unknown;
  /** End-user identifier. Prefix with ISO country code, e.g. "KH12345". */
  userId?: string;
  /** Application or document identifier (free-form). */
  issue?: string;
}

export interface XRoadCallResult<T = unknown> {
  request: {
    method: XRoadHttpMethod;
    url: string;
    headers: Record<string, string>;
    body: string | null;
  };
  response: {
    status: number;
    statusText: string;
    headers: Record<string, string>;
    body: T | string | null;
  };
}
